version: '3.8'

services:
  discord-bot:
    build:
      context: .
      dockerfile: once-human-bot/Dockerfile
    container_name: once-human-bot
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - HEALTH_CHECK_PORT=3000
    ports:
      - "3000:3000"
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "
        const http = require('http');
        const options = {
          hostname: '127.0.0.1',
          port: process.env.HEALTH_CHECK_PORT || 3000,
          path: '/health',
          timeout: 10000
        };
        const req = http.request(options, (res) => {
          let data = '';
          res.on('data', chunk => data += chunk);
          res.on('end', () => {
            try {
              const health = JSON.parse(data);
              process.exit(health.status === 'healthy' ? 0 : 1);
            } catch (e) {
              process.exit(res.statusCode === 200 ? 0 : 1);
            }
          });
        });
        req.on('error', (e) => {
          console.error('Health check error:', e.message);
          process.exit(1);
        });
        req.on('timeout', () => {
          console.error('Health check timeout');
          process.exit(1);
        });
        req.setTimeout(10000);
        req.end();
      "]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

networks:
  app-network:
    driver: bridge
    name: once-human-network