version: '3.8'

# Local development overrides
# This file is automatically loaded by docker-compose in development
# It will NOT be used in production (Coolify uses docker-compose.prod.yml)

services:
  rag-service:
    ports:
      - "5000:5000"  # Expose RAG service for local testing
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - LOG_LEVEL=DEBUG
    volumes:
      # Mount source code for hot reloading
      - ./rag_pipeline:/app/rag_pipeline:ro
      - ./OncehumanPDFs:/app/OncehumanPDFs:ro
      # Development data directories
      - ./dev-data/chroma_db:/data/chroma_db
      - ./dev-data:/data
      - ./dev-data/model_cache:/app/model_cache
    command: ["python3", "-m", "flask", "--app", "rag_pipeline.rag_service", "run", "--host", "0.0.0.0", "--port", "5000", "--reload"]

  discord-bot:
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
    volumes:
      # Mount source code for development
      - ./once-human-bot:/app/once-human-bot:ro
      - ./package.json:/app/package.json:ro
      - ./package-lock.json:/app/package-lock.json:ro
      - ./rag_pipeline/game_entities.json:/app/rag_pipeline/game_entities.json:ro
      # Development database
      - ./dev-data:/data
    # Use nodemon for auto-restart on file changes
    command: ["npx", "nodemon", "--watch", "once-human-bot", "--ext", "js,json", "once-human-bot/index.js"]
    
  # Optional: Add a database viewer for development
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - ADMINER_DEFAULT_SERVER=sqlite
    volumes:
      - ./dev-data:/data
    profiles:
      - debug

# Override volumes to use local directories in development
volumes:
  chroma_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./dev-data/chroma_db
  sqlite_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./dev-data
  model_cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./dev-data/model_cache