# fly.toml file generated for your app

app = "once-human-bot-and-rag" # You can change this to your preferred app name
primary_region = "sin" # Example region, choose one close to you or your users

[build]
  dockerfile = "Dockerfile"

[vm]
  size = "shared-cpu-4x" # 1GB RAM

[processes]
  rag = "python3 /app/rag_pipeline/rag_service.py"
  bot = "node /app/once-human-bot/index.js"

[[services]]
  internal_port = 5000
  processes = ["rag"]
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"

[[mounts]]
  source = "chroma_data"
  destination = "/data"