# fly.toml file generated for your app

app = "once-human-bot-and-rag" # You can change this to your preferred app name
primary_region = "sin" # Example region, choose one close to you or your users

[build]
  dockerfile = "Dockerfile"

[vm]
  size = "shared-cpu-4x" # 1GB RAM

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"

[[mounts]]
  source = "chroma_data"
  destination = "/data"